### ISSUE TITLE
[Bug] Server crash after /manhunt start

### ISSUE THREAD

**Issue by duKYyyy** [anhgelus/manhunt-mod#5]
this is what i get in crash log
Time: 2024-12-27 16:41:26
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.class_4174.<init>(int, float, boolean, float, java.util.Optional, java.util.List)'
	at knot//world.anhgelus.manhunt.Manhunt.lambda$onInitialize$10(Manhunt.java:115)
	at knot//com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
	at knot//net.minecraft.class_8865.method_54416(class_8865.java:29)
	at knot//net.minecraft.class_8865.execute(class_8865.java:13)
	at knot//net.minecraft.class_8856.method_54405(class_8856.java:8)
	at knot//net.minecraft.class_8847.method_54388(class_8847.java:8)
	at knot//net.minecraft.class_8854.method_54390(class_8854.java:107)
	at knot//net.minecraft.class_2170.method_54313(class_2170.java:384)
	at knot//net.minecraft.class_2170.method_9249(class_2170.java:314)
	at knot//net.minecraft.class_3244.method_58590(class_3244.java:1433)
	at knot//net.minecraft.class_3244.method_44356(class_3244.java:1421)
	at knot//net.minecraft.class_3738.run(class_3738.java:18)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:164)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:889)
	at knot//net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:180)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:138)
	at knot//net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:871)
	at knot//net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:865)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:123)
	at knot//net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:833)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:719)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by anhgelus** [comment]
Which version of Minecraft and of the mod are you using?

**Comment by duKYyyy** [comment]
the server is 1.21.4 and the mod is the latest 1.1.1
and a nother thing, after i call the track command, it only tracks like
only the position where that player was


În vin., 27 dec. 2024 la 17:19, William Hergès ***@***.***> a
scris:

**Comment by anhgelus** [comment]
Thank you for your report, I'm going to check that when I have time.

The compass starts to update automatically when the game starts, this is why it is not updated. You can update it manually by using the same command.

**Comment by duKYyyy** [comment]
ok thanks


În vin., 27 dec. 2024 la 17:45, William Hergès ***@***.***> a
scris:

**Comment by anhgelus** [comment]
As written on Modrinth, the mod does not support (yet) the 1.21.4. Minecraft 1.21.2 or Minecraft 1.21.3 must work. I will check this later for these versions.

If the mod works for 1.21.2 and 1.21.3, I will close this issue as unplanned (but I will update my mod for 1.21.4 when I have time).
